export enum Notes {
    IS_FETCHING = 'IS_FETCHING',
    IS_ADDING = 'IS_ADDING',
    GET_ALL = 'GET_ALL',
    ADD = 'ADD',
    UPDATE = 'UPDATE',
    DELETE = 'DELETE',
    SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
}